def get_channel_item_listingsrc_all(chan_name):
    try:
        return channels['channels'][chan_name]
    except Exception as e:
        print('ERROR - ' + str(e))
        return False


def get_channel_item_listingsrc(chan_name, src):
    try:
        item = get_channel_item_listingsrc_all(chan_name)
        if bool(item):
            return item[src]
        return False
    except Exception as e:
        print('ERROR - ' + str(e))
        return False


channels = {"BBC ONE": {"bleb": "bbc1"},
            "BBC TWO": {"bleb": "bbc2"},
            "ITV": {"bleb": "p_itv1"},
            "Channel 4": {"bleb": "ch4"},
            "Channel 4 +1": {},
            "Channel 5": {"bleb": "five"},
            "Channel 5 +1": {},
            "My5": {},
            "BBC FOUR": {"bleb": "bbc4"},
            "Sky1": {"bleb": "sky_one"},
            "Sky2": {"bleb": "sky_two"},
            "Sky Living": {"bleb": "living_tv"},
            "Sky Living +1": {},
            "ITV +1": {},
            "ITV2": {"bleb": "p_itv2"},
            "ITV2 +1": {},
            "ITV3": {"bleb": "p_itv3"},
            "ITV3 +1": {},
            "ITV4": {"bleb": "p_itv4"},
            "ITV4 +1": {},
            "ITVBe": {},
            "ITVBe +1": {},
            "Sky Arts": {},
            "Pick": {},
            "W": {"bleb": "watch"},
            "W +1": {},
            "Gold": {"bleb": "uk_gold"},
            "Gold +1": {},
            "Dave": {"bleb": "dave"},
            "Dave ja vu": {},
            "Alibi": {},
            "Alibi +1": {},
            "Comedy Central": {"bleb": "paramount"},
            "Comedy Central +1": {},
            "Comedy Central Extra": {"bleb": "paramount2"},
            "MTV": {"bleb": "mtv"},
            "syfy": {"bleb": "scifi"},
            "syfy +1": {},
            "Universal Channel": {},
            "Universal Channel +1": {},
            "Challenge": {"bleb": "challenge"},
            "Challenge +1": {},
            "E4": {"bleb": "e4"},
            "E4 +1": {},
            "More4": {"bleb": "more4"},
            "More4 +1": {},
            "CBS Reality": {},
            "CBS Reality +1": {},
            "Horror Channel": {},
            "Horror Channel +1": {},
            "5*": {"bleb": "fiver"},
            "5* +1": {},
            "5 USA": {},
            "5 USA +1": {},
            "5 Spike": {},
            "E! Entertainment": {},
            "FOX": {"bleb": "fx"},
            "FOX +1": {},
            "Made in Leeds": {},
            "Real Lives": {},
            "Real Lives +1": {},
            "BBC ALBA": {},
            "S4C": {"bleb": "s4c"},
            "TLC": {},
            "TLC +1": {},
            "DMAX": {},
            "DMAX +1": {},
            "Quest": {},
            "Quest +1": {},
            "BET": {},
            "True Entertainment": {},
            "Drama": {},
            "CBS Action": {},
            "Sony TV": {},
            "4Seven": {},
            "CBS Drama": {},
            "TruTV": {},
            "Sky Cinema Premiere": {"bleb": "sky_movies_premiere"},
            "Sky Cinema Premiere +1": {},
            "Sky Cinema Hits": {"bleb": "sky_movies_showcase"},
            "Sky Cinema Greats": {"bleb": "sky_movies_modern_greats"},
            "Sky Cinema Disney": {},
            "Sky Cinema Family": {"bleb": "sky_movies_family"},
            "Sky Cinema Action": {"bleb": "sky_movies_action_thriller"},
            "Sky Cinema Comedy": {"bleb": "sky_movies_comedy"},
            "Sky Cinema Thriller": {"bleb": "sky_movies_crime_thriller"},
            "Sky Cinema Drama": {"bleb": "sky_movies_drama"},
            "Sky Cinema Sci Fi & Horror": {"bleb": "sky_movies_sci-fi_horror"},
            "Sky Cinema Select": {"bleb": "sky_movies_indie"},
            "TCM": {"bleb": "tcm"},
            "TCM +1": {},
            "Movies 24": {},
            "Movies 24 +1": {},
            "True Movies": {},
            "Sony Movie Channel": {},
            "Film4": {"bleb": "film_four"},
            "Film4 +1": {},
            "Sky Sports News": {"bleb": "sky_sports_news"},
            "Sky Sports Mix": {},
            "Sky Sports Main Event": {},
            "Sky Sports Premier League": {},
            "Sky Sports Football": {},
            "Sky Sports Cricket": {},
            "Sky Sports Golf": {},
            "Sky Sports F1": {},
            "Sky Sports Action": {},
            "Sky Sports Arena": {},
            "At The Races": {},
            "BT Sport 1": {},
            "BT Sport 2": {},
            "BT Sport 3": {},
            "BT Sport ESPN": {},
            "Eurosport 1": {"bleb": "british_eurosport"},
            "Eurosport 2": {},
            "Motorsport TV": {},
            "FIA Formula E": {},
            "BIKE": {},
            "COPA90": {},
            "Yesterday": {},
            "Yesterday +1": {},
            "Eden": {},
            "Eden +1": {},
            "Discovery Channel": {},
            "Discovery Channel +1": {},
            "Investigation Discovery": {},
            "Investigation Discovery +1": {},
            "Animal Planet": {},
            "Animal Planet +1": {},
            "Discovery Science": {},
            "Discovery Science +1": {},
            "Discovery Turbo": {},
            "Discovery History": {},
            "Discovery History +1": {},
            "Nat Geo Wild": {},
            "National Geographic": {},
            "National Geographic +1": {},
            "Community Channel": {},
            "History": {},
            "History +1": {},
            "H2": {},
            "Lifetime": {},
            "Crime and Investigation": {},
            "PBS America": {},
            "Forces TV": {},
            "Good Food": {},
            "Good Food +1": {},
            "Food Network": {},
            "Home": {"bleb": "uktv_style"},
            "Home +1": {},
            "Really": {},
            "Discovery Home & Health": {},
            "Discovery Home & Health +1": {},
            "Discovery Shed": {},
            "Ginx Esports TV": {},
            "Travel Channel": {},
            "CBBC": {"bleb": "cbbc"},
            "Cbeebies": {"bleb": "cbeebies"},
            "Cartoon Network": {"bleb": "cartoon_network"},
            "Cartoon Network +1": {},
            "Cartoonito": {},
            "Disney XD": {},
            "Disney XD +1": {},
            "Nickelodeon": {"bleb": "nickelodeon"},
            "Nickelodeon +1": {},
            "Nick Junior": {},
            "Nick Junior Too": {},
            "Nick Toons": {},
            "Disney Channel": {"bleb": "disney"},
            "Disney Channel +1": {},
            "Disney Junior": {},
            "Boomerang": {},
            "Boomerang +1": {},
            "CITV": {"bleb": "citv"},
            "Pop": {},
            "Tiny Pop": {},
            "MTV Music": {},
            "MTV Live HD": {},
            "MTV Hits": {},
            "MTV Base": {},
            "MTV Dance": {},
            "MTV Rocks": {},
            "VH1": {"bleb": "vh1"},
            "Viva": {},
            "4 Music": {"bleb": "4music"},
            "The Box": {},
            "Kiss": {},
            "Box Hits": {},
            "Box Upfront": {},
            "Magic": {},
            "Kerrang! TV": {},
            "Vintage TV": {},
            "Clubland": {},
            "BBC News": {"bleb": "bbc_news24"},
            "Sky News": {"bleb": "sky_news"},
            "BBC Parliament": {"bleb": "bbc_parliament"},
            "CNN": {},
            "Bloomberg": {"bleb": "boomerang"},
            "CNBC": {},
            "Euronews": {},
            "NDTV 24x7": {},
            "BBC Radio 1": {},
            "BBC Radio 1 Xtra": {},
            "BBC Radio 2": {},
            "BBC Radio 3": {},
            "BBC Radio 4 FM": {},
            "BBC Radio 4 Extra": {},
            "BBC Radio 4 Long Wave": {},
            "BBC Radio 5 Live": {},
            "BBC Radio 5 Live Sports Extra": {},
            "BBC Radio 6 Music": {},
            "BBC World Service": {},
            "Absolute Radio": {},
            "Smooth Radio": {},
            "Heart FM": {},
            "LBC": {},
            "Classic FM": {},
            "Gold Radio": {},
            "Planet Rock": {},
            "Magic Radio": {},
            "Absolute 80s": {},
            "Absolute Classic Rock": {},
            "Capital FM": {},
            "Capital Xtra": {},
            "Radio X": {},
            "Kiss FM": {},
            "talkSPORT": {}
            }
